#!/bin/bash

# 1  SIGHUP  Close terminal
# 2  SIGINT  Ctrl+C
# 9  SIGKILL
# 18 SIGTSTP Ctrl+Z

trap "echo ' Trapped Ctrl+C'" SIGINT
trap "echo Bye!" EXIT

i=0

while [ $i -le 5 ]
do
  echo "N #$i"
  sleep 1
  i=$[ $i + 1 ]
done
